require:
  - standard/cop/block_single_line_braces
  - rubocop-performance
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'Gemfile'
    - 'gemfiles/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 3.1.3

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashConversion:
  Enabled: false

Naming/FileName:
  Exclude:
   - '**/*.md'
  
Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
