require:
  - standard/cop/block_single_line_braces
  - rubocop-performance
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'Gemfile'
    - 'gemfiles/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 3.2.2

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashConversion:
  Enabled: false

Style/EndlessMethod:
  EnforcedStyle: allow_always

Naming/FileName:
  Exclude:
   - '**/*.md'

Layout/LineLength:
  Max: 120
  
Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/SpaceInsideHashLiteralBraces: 
  EnforcedStyle: space

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Layout/EmptyLineBetweenDefs:
  Enabled: false
  